#!/bin/bash

#$1 is ethernet, wifi, vpn
#( global
nm_type="$1"
action_up="c up"
action_down="c down"
id_regex='[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'

case $nm_type in
  wifi)
    nm_icon=""
    nm_active=$(LC_ALL=C nmcli -c no -f active,bssid dev wifi list | grep --color=never -E "^yes" | grep --color=never -Eoi "([0-9A-F]{2}:){5}[0-9A-F]{2}")
    nm_all=$(nmcli -c no -f security,bars,ssid,bssid dev wifi list | sed "s/^\(WPA.\|WEP\).*▂/ ▂/g"|sed "s/^--.*▂/  ▂/g")
    action_up="d wifi connect"
    action_down="d wifi disconnect"
    id_regex='([0-9A-F]{2}:){5}[0-9A-F]{2}'
    ;;
  vpn)
    nm_icon="旅"
    nm_active=$(nmcli -c no -f uuid,type c show --active | grep --color=never -E "($nm_type|wireguard)"' *$' | sed "s/ \{1,\}$nm_type *//g" | sed "s/ \{1,\}\(wireguard\|vpn\) *//g")
    nm_all=$(nmcli -c no -f name,uuid,type c show | grep --color=never -E "($nm_type|wireguard)"' *$' | sed "s/ \{1,\}\(wireguard\|vpn\) *//g")
    ;;
  ethernet)
    nm_icon="酪"
    nm_active=$(nmcli -c no -f uuid,type c show --active | grep --color=never -E "$nm_type"' *$' | sed "s/ \{1,\}$nm_type *//g")
    nm_all=$(nmcli -c no -f name,uuid,type c show | grep --color=never -E "$nm_type"' *$' | sed "s/ \{1,\}$nm_type *//g")
    ;;
  bluetooth)
    nm_icon=" "
    nm_active=$(nmcli -c no -f uuid,type c show --active | grep --color=never -E "$nm_type"' *$' | sed "s/ \{1,\}$nm_type *//g")
    nm_all=$(nmcli -c no -f name,uuid,type c show | grep --color=never -E "$nm_type"' *$' | sed "s/ \{1,\}$nm_type *//g")
    ;;
esac
nm_menu="menus/$nm_type"

#)

#( main
echo "declare -A am_items=(" > "$nm_menu"
echo "  ['  ..']='anymenu network'" >> "$nm_menu"
IFS=$'\r\n'

for n in $(echo "$nm_all" | grep --color=never -Eoi "$id_regex" ); do
  active="  " # The first char here is an unicode space so the active one is sorted first
  action="$action_up"
  name="$(echo "$nm_all" | grep --color=never -E "$n" | sed "s/ *$n *//g" | tr \' \`)"
  if echo "$nm_active" | grep --color=never -Eq "^$n\$"; then
    active="  "
    action="$action_down"
  fi
  echo "  ['$nm_icon$active$name']='nmcli $action $n'" >> "$nm_menu"
done

echo ")" >> "$nm_menu"
anymenu "$(basename "$nm_menu")"
rm -f "$nm_menu"
#)
